"""
utils/exporter.py — Structured output export for the literature review pipeline.

Exports the final synthesized review and source metadata in three formats:
  • Markdown  — Human-readable formatted report for reading/sharing.
  • BibTeX    — Machine-readable citation format for reference managers (Zotero, Mendeley, etc.).
  • JSON      — Structured data format for downstream processing or APIs.

All files are written to an `outputs/` directory organised by a timestamp-based run ID.
"""

import json
import os
import re
from datetime import datetime
from typing import Dict, List


def _make_run_dir(output_dir: str = "outputs") -> str:
    """Creates a timestamped directory for this export run and returns its path."""
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(output_dir, run_id)
    os.makedirs(run_dir, exist_ok=True)
    return run_dir


def _sanitise_bibtex_key(text: str) -> str:
    """Produces a clean alphanumeric BibTeX citation key from arbitrary text."""
    key = re.sub(r"[^a-zA-Z0-9]", "", text.replace(" ", "_"))
    return key[:30] if key else "unknown"


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------

def export_markdown(
    query: str,
    review_text: str,
    docs: List[Dict],
    run_dir: str,
) -> str:
    """
    Writes a formatted Markdown literature review report.

    Sections:
      - Title + generation timestamp
      - Research query
      - Synthesized review (verbatim LLM output)
      - Source documents table (title, authors, year, filename)
    """
    lines = [
        "# Automated Literature Review",
        "",
        f"**Research Query:** {query}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
        "## Synthesized Review",
        "",
        review_text.strip(),
        "",
        "---",
        "",
        "## Source Documents",
        "",
        "| # | Title | Authors | Year | File |",
        "|---|-------|---------|------|------|",
    ]

    for i, doc in enumerate(docs, 1):
        meta = doc.get("metadata", {})
        title   = meta.get("title",   meta.get("filename", "Unknown"))
        authors = meta.get("authors", "Unknown Authors")
        year    = meta.get("year",    "Unknown Year")
        fname   = meta.get("filename", meta.get("source", "—"))
        lines.append(f"| {i} | {title} | {authors} | {year} | `{fname}` |")

    lines += ["", "---", "_Report generated by Multi-Agent RAG Literature Review System_", ""]

    path = os.path.join(run_dir, "review.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[Exporter] Markdown saved → {path}")
    return path


# ---------------------------------------------------------------------------
# BibTeX export
# ---------------------------------------------------------------------------

def export_bibtex(docs: List[Dict], run_dir: str) -> str:
    """
    Generates a .bib file from source document metadata.

    Each unique source file becomes one @misc BibTeX entry.
    Deduplication is by filename so the same paper doesn't appear twice
    even if multiple chunks from it were retrieved.
    """
    seen_files: set = set()
    entries: List[str] = []

    for doc in docs:
        meta = doc.get("metadata", {})
        fname = meta.get("filename", meta.get("source", "unknown"))

        if fname in seen_files:
            continue
        seen_files.add(fname)

        title   = meta.get("title",   os.path.splitext(fname)[0])
        authors = meta.get("authors", "Unknown Authors")
        year    = meta.get("year",    "Unknown")
        source  = meta.get("source",  fname)

        key = _sanitise_bibtex_key(f"{authors.split()[0]}{year}{title[:10]}")

        entry = (
            f"@misc{{{key},\n"
            f"  title   = {{{title}}},\n"
            f"  author  = {{{authors}}},\n"
            f"  year    = {{{year}}},\n"
            f"  note    = {{Source: {source}}},\n"
            f"}}"
        )
        entries.append(entry)

    path = os.path.join(run_dir, "references.bib")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n\n".join(entries))

    print(f"[Exporter] BibTeX saved  → {path}")
    return path


# ---------------------------------------------------------------------------
# JSON export
# ---------------------------------------------------------------------------

def export_json(
    query: str,
    review_text: str,
    docs: List[Dict],
    run_dir: str,
) -> str:
    """
    Saves the full pipeline output as structured JSON for downstream use.

    Schema:
      {
        "query":          str,
        "generated_at":   ISO-8601 timestamp,
        "review":         str,
        "source_count":   int,
        "sources": [
          { "title", "authors", "year", "filename", "content_preview" }
        ]
      }
    """
    sources = []
    seen_files: set = set()

    for doc in docs:
        meta  = doc.get("metadata", {})
        fname = meta.get("filename", meta.get("source", "unknown"))
        if fname in seen_files:
            continue
        seen_files.add(fname)

        sources.append({
            "title":           meta.get("title",   fname),
            "authors":         meta.get("authors", "Unknown"),
            "year":            meta.get("year",    "Unknown"),
            "filename":        fname,
            "content_preview": doc.get("content", "")[:200].strip(),
        })

    payload = {
        "query":        query,
        "generated_at": datetime.now().isoformat(),
        "review":       review_text.strip(),
        "source_count": len(sources),
        "sources":      sources,
    }

    path = os.path.join(run_dir, "report.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)

    print(f"[Exporter] JSON saved    → {path}")
    return path


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def export_all(
    query: str,
    review_text: str,
    docs: List[Dict],
    output_dir: str = "outputs",
) -> Dict[str, str]:
    """
    Runs all three exporters in a single timestamped output directory.

    Returns:
        dict with keys "markdown", "bibtex", "json" pointing to written file paths.
    """
    run_dir = _make_run_dir(output_dir)
    print(f"\n[Exporter] Writing outputs to: {run_dir}")

    paths = {
        "markdown": export_markdown(query, review_text, docs, run_dir),
        "bibtex":   export_bibtex(docs, run_dir),
        "json":     export_json(query, review_text, docs, run_dir),
    }

    print(f"[Exporter] All formats written ✓")
    return paths
